
Can I  combine course plans to provide upgrades for a single course?
--------------------------------------------------------------------------

**YES**

For example, if you expect 35 students in a course, you could buy one Extra Small plan for 10 students, and one Small plan for 25 students.

Can I teach multiple courses with a single plan?
-------------------------------------------------------

**YES**

Upgrades can be mixed and distributed in a very flexible way.
For example, if you are teaching one course with 30 students and another with 40 students, you could buy a single Medium plan for 70 students,
and then allocate upgrades for student projects for the two courses accordingly.

In general, upgrades of the same type, for example Member Hosting, are interchangeable.
It doesn't matter if the upgrade comes from a personal subscription or course plan.
An upgrade can be applied to one project, removed from that, and applied to another project. This can be done as many times as desired until the upgrade expires.

Both the above questions apply to :ref:`inst-pays`, described in detail below.